In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [7]:
b=np.array([4,5,6])

In [8]:
b

array([4, 5, 6])

In [9]:
a+b

array([5, 7, 9])

In [10]:
z=np.add(a,b)

In [11]:
z

array([5, 7, 9])

In [18]:
a

array([1, 2, 3])

In [19]:
b

array([4, 5, 6])

In [20]:
print(a)
print(b)

[1 2 3]
[4 5 6]


In [21]:
a[2]=10

In [27]:
c=np.array([[1,2,3] ,[4,5,6]])

In [28]:
print(c)

[[1 2 3]
 [4 5 6]]


In [33]:
c[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
c[1:]

array([[4, 5, 6]])

In [35]:
c[2:]

array([], shape=(0, 3), dtype=int32)

In [37]:
c[:1]

array([[1, 2, 3]])

In [38]:
c[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
c[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
c[1:2]

array([[4, 5, 6]])

In [41]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
c[0]

array([1, 2, 3])

In [43]:
c[1]

array([4, 5, 6])

In [44]:
c[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
c[:1]

array([[1, 2, 3]])

In [46]:
c[:5]

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
c:5

In [51]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
c*5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [53]:
c[1]=20

In [54]:
c

array([[ 1,  2,  3],
       [20, 20, 20]])

In [55]:
c[0]=10

In [56]:
c

array([[10, 10, 10],
       [20, 20, 20]])

In [57]:
c[1:1]

array([], shape=(0, 3), dtype=int32)

In [58]:
c[0:0]

array([], shape=(0, 3), dtype=int32)

In [59]:
c/2

array([[ 5.,  5.,  5.],
       [10., 10., 10.]])

In [62]:
c

array([[10, 10, 10],
       [20, 20, 20]])

In [63]:
print(c)

[[10 10 10]
 [20 20 20]]


In [64]:
for i in c:
    print(c)

[[10 10 10]
 [20 20 20]]
[[10 10 10]
 [20 20 20]]


In [65]:
c/2

array([[ 5.,  5.,  5.],
       [10., 10., 10.]])

In [66]:
c/2

array([[ 5.,  5.,  5.],
       [10., 10., 10.]])

In [67]:
a=c/2

In [68]:
a/2

array([[2.5, 2.5, 2.5],
       [5. , 5. , 5. ]])

In [69]:
a/2.5

array([[2., 2., 2.],
       [4., 4., 4.]])

In [70]:
e=a/2.5

In [71]:
e

array([[2., 2., 2.],
       [4., 4., 4.]])

In [72]:
f=e/2

In [73]:
f

array([[1., 1., 1.],
       [2., 2., 2.]])

In [77]:
f

array([[1., 1., 1.],
       [2., 2., 2.]])

In [78]:
g=f*2

In [79]:
g

array([[2., 2., 2.],
       [4., 4., 4.]])

In [82]:
g

array([[2., 2., 2.],
       [4., 4., 4.]])

In [85]:
a

array([[ 5.,  5.,  5.],
       [10., 10., 10.]])

In [86]:
b

array([4, 5, 6])

In [89]:
True+1

2

In [90]:
False-1

-1

In [91]:
8**2

64

In [92]:
w=['a','b']

In [93]:
w.append('c')

In [94]:
w

['a', 'b', 'c']

In [95]:
z in w

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  """Entry point for launching an IPython kernel.


False

In [96]:
z

array([5, 7, 9])

In [97]:
g

array([[2., 2., 2.],
       [4., 4., 4.]])

In [98]:
b

array([4, 5, 6])

In [99]:
a

array([[ 5.,  5.,  5.],
       [10., 10., 10.]])

In [100]:
z+b

array([ 9, 12, 15])

In [101]:
z[0]

5

In [102]:
z+b[1]

array([10, 12, 14])

In [103]:
z*2

array([10, 14, 18])

In [104]:
z

array([5, 7, 9])

In [106]:
for i in z:
    i=i*2
    print(i)
b=i

10
14
18


In [107]:
b

18

In [108]:
10 in z

False

In [110]:
9 in z

True

-5**2

In [111]:
-5**2

-25

In [112]:
(-5)**2

25

In [113]:
(-5)**3

-125

In [114]:
-5**3

-125

In [115]:
i=True+1

In [116]:
i

2

In [117]:
j=(1,2,3)

In [118]:
j*2

(1, 2, 3, 1, 2, 3)

In [122]:
j*10

(1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3)

In [123]:
type(j)

tuple

In [126]:
j*2

(1, 2, 3, 1, 2, 3)

In [127]:
j*3

(1, 2, 3, 1, 2, 3, 1, 2, 3)